name: rdp-2k-manual

on:
  workflow_dispatch:
    inputs:
      performance_tool:
        description: "k6 or JMeter"
        required: true
        default: "k6"
        type: choice
        options:
          - k6
          - JMeter
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  run-rdp-2k-on-JMeter:
    if: ${{ github.event.inputs.performance_tool == 'JMeter' }}
    name: Running rdp 2k test with JMeter
    runs-on: ubuntu-latest
    steps:
      - name: Run JMeter 2k test
        uses: rbhadti94/apache-jmeter-action@v0.7.0
        with:
          testFilePath: rdp-2k-users.jmx
          outputReportsFolder: reports/

  run-rdp-2k-on-k6:
    if: ${{ github.event.inputs.performance_tool == 'k6' }}
    name: Running rdp 2k test with k6
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Run local k6 test
        uses: grafana/k6-action@v0.2.0
        with:
          filename: rdp-2k-csv.js
          flags: --out json=results.json

      - name: Upload performance test results
        uses: actions/upload-artifact@v3
        with:
          name: k6-report
          path: results.json